### ISSUE TITLE
Bio_all from sprseries isn't right.

### ISSUE THREAD

**Issue by taylori** [melmonk/StockAssessment_template#12]
For reasons that I haven't yet figured out, the Bio_all column in the sprseries is not the same as the Bio_all column in timeseries.  Changing from `sprseries` to `timeseries` in this line of Assessment_template.Rmd seems to fix it.
```
    Bio_all = mod1$sprseries[, c('Yr', 'Bio_all')]
```
@CWetzel made other refinements to this table for the POP model that could be included in the template in the future.

**Comment by melmonk** [comment]
Thank you @taylori

**Comment by melmonk** [comment]
This should be fixed with the newest r4SS versions and modifications to the template.
